### ISSUE TITLE
Stops downloading at the 3rd depth

### ISSUE THREAD

**Issue by WeirdPlatypus** [theslavicbear/Ebook-Publisher#100]
Hello,

I have an issue with in a CHYOA story where it does not download further than the third depth (https://chyoa.com/index.php/story/A-Different-Kind-Of-Lesson.10630).

It detects the right number of chapter but just stops without error. It is the same if I try to download from a deeper chapter.

**Comment by theslavicbear** [comment]
Thanks, will be fixed with the next release, or pull the 3.3.3 patch branch to use it now. I guess they changed the layouts of the URLs there, causing my code that checks linked chapters to pick up every chapter after the first few as a duplicate.
