### ISSUE TITLE
follow link that go back to beguining infinitely (until max recursion depth) when downloading from chyoa.com  

### ISSUE THREAD

**Issue by reuspppp** [theslavicbear/Ebook-Publisher#52]
in [this](https://chyoa.com/story/Normality.6104) story the program follow the link from [this](https://chyoa.com/chapter/Some-more-words-to-more-readers.263106) chapter infinitely

**Comment by theslavicbear** [comment]
Infinite recursion due to links to previous pages should be fixed now. The linked pages still get added, but none of their child pages will be added.

**Comment by reuspppp** [comment]
thanks :D
