### ISSUE TITLE
got "IndexError: list index out of range" while downloading from chyoa.com

### ISSUE THREAD

**Issue by reuspppp** [theslavicbear/Ebook-Publisher#53]
while downloading [this](https://chyoa.com/story/Chronicles-of-a-College-Hypnotist.29073) story I got the following error :

![image](https://user-images.githubusercontent.com/68921748/89131377-a69f4100-d50c-11ea-95d9-aa2f3ea7268c.png)

it did not stop the program but it froze after a while and did not finish downloading

**Comment by theslavicbear** [comment]
Do you mind sharing the link/links you used for this? If it fails with the -t option, you can also try without the -t option, though it will run much slower.

**Comment by reuspppp** [comment]
link of the story : https://chyoa.com/story/Chronicles-of-a-College-Hypnotist.29073

**Comment by reuspppp** [comment]
the page that crash the program : https://chyoa.com/chapter/The-town-pool.767691  (now I get an error trying to access it)

**Comment by theslavicbear** [comment]
There's nothing I can do to fix the server error for that page, though Ebook-Publisher just ignores it and writes the rest of the pages anyway. I'm guessing the better request handling I added helped in this case, since the original error pops up if the correct page html document wasn't returned.
