### ISSUE TITLE
get error related to internet connection even if my connection is fine

### ISSUE THREAD

**Issue by reuspppp** [theslavicbear/Ebook-Publisher#54]
I get this error :

![image](https://user-images.githubusercontent.com/68921748/89131822-df8ce500-d50f-11ea-94e5-12c47c85139c.png)
 
it also cause the program to run infinitely after the error with multi-threading (download without stopping even after having exceeded the number of chapters) 

my internet connection is working, but maybe its not always stable ? maybe adding something to retry to download the page after a minute or something like that.

**Comment by theslavicbear** [comment]
Yeah I was considering writing better functions to handle the requests that would hopefully be less error prone.

**Comment by theslavicbear** [comment]
Added better http request handling (for chyoa at least) and tested with very long story. Should be considered fixed now.
