### ISSUE TITLE
Comparison operator typo in Common.py

### ISSUE THREAD

**Issue by DennisPing** [theslavicbear/Ebook-Publisher#55]
I'm a beginner and not proficient in pull requests. So, I'm submitting it manually here:

In Common.py line 101 please fix:
`if attempts => 5:` to `if attempts >= 5:`

Just a simple typo from the latest commit https://github.com/theslavicbear/Ebook-Publisher/commit/469c534fbe01796168c2a2a93bd0170e5ca20bbd

**Comment by theslavicbear** [comment]
Good catch. I had already fixed this but never committed it. Fixed in v3.1.3
