### ISSUE TITLE
choya - Does not stop on 502 Error

### ISSUE THREAD

**Issue by SomeRandomDude870** [theslavicbear/Ebook-Publisher#62]
Hey, I have just used:
`Ebook-Publisher.py https://chyoa.com/story/Contagion-63X---Viral-Transformation.26118 -o epub -o html -o txt -i`

 the problem is that I got an:
`==========Server returned status code 502 for page: https://chyoa.com/chapter/A-redhead-looking-for-something-to-lick.793955
Could not complete request for page: https://chyoa.com/chapter/A-redhead-looking-for-something-to-lick.793955
Server returned status code 502 for page: https://chyoa.com/chapter/A-young-man-at-the-beach-with-his-sister-and-her-boyfriend.793956
Could not complete request for page: https://chyoa.com/chapter/A-young-man-at-the-beach-with-his-sister-and-her-boyfriend.793956
Server returned status code 502 for page: https://chyoa.com/chapter/A-girl-with-a-love-for-popsicles.793959
Could not complete request for page: https://chyoa.com/chapter/A-girl-with-a-love-for-popsicles.793959
Server returned status code 502 for page: https://chyoa.com/chapter/A-couple-hungry-for-sex-barge-in-on-Pamela.793960
Could not complete request for page: https://chyoa.com/chapter/A-couple-hungry-for-sex-barge-in-on-Pamela.793960
======================================================================================================`

between the download and after that it did neither stop nor complete.
It just kept on producing ==== constantly, for over two hours.

Due to this it´s not possible to download this one.

Additionally, it takes a lot of time until this error is thrown, this story has way fewer chapters than some others, but it takes several times more time to get to this error.

I have tried to download it a second time, but it only has produced === for half an hour or so now.

**Comment by theslavicbear** [comment]
I think the never ending progress bar is because I never added the backwards link checking in the single threaded methods.

**Comment by theslavicbear** [comment]
This should be fixed by v3.1.4
