### ISSUE TITLE
chyoa - Object has no attribute

### ISSUE THREAD

**Issue by SomeRandomDude870** [theslavicbear/Ebook-Publisher#63]
If I use:
`Ebook-Publisher.py https://chyoa.com/story/Healslut-Adventures.29070 -o epub -o html -i`

I get the error:
`Traceback (most recent call last):
  File "E:\Firefox Downloads\Ebook-Publisher-3.1.3\Ebook-Publisher.py", line 295, in <module>
    formats[ft](clas)
  File "E:\Firefox Downloads\Ebook-Publisher-3.1.3\Ebook-Publisher.py", line 32, in <lambda>
    'epub':lambda x:MakeEpub(x),
  File "E:\Firefox Downloads\Ebook-Publisher-3.1.3\Ebook-Publisher.py", line 158, in MakeEpub
    zeros = '0' * (len(str(site.isize))-1)
AttributeError: 'Chyoa' object has no attribute 'isize'
`

It is thrown for html and txt.
It is thrown for epub too, however the epub will be created and filled with content unlike the other two.

**Comment by theslavicbear** [comment]
Tried testing this again. Did not receive any error. Might have been a server error thrown in your case. Request you try again with most recent commit (i.e. clone the repo rather than the latest release) and report back.

**Comment by theslavicbear** [comment]
If this is still an issue it should be fixed in v3.1.4
