### ISSUE TITLE
Add update function

### ISSUE THREAD

**Issue by SomeRandomDude870** [theslavicbear/Ebook-Publisher#64]
Hi, I would like to recommend making it possible to update my downloaded stories automatically. 

_I thought about it like that:_
1.) create a default save directory archive/database
2.) Either add a database, a file with a simple key/value pair, being the Name of the story and the download URL or add it to the metadata of the story. Or whatever is easiest for you.
3.) add the command "update"
4.) by update it will update all the stories in the database. Don´t know how it´s easier for you - downloading completely or updating the existing file.

**Comment by theslavicbear** [comment]
You can somewhat already do this if you create a text file with all the URLs you want to download, then use an aliased command (or whatever the windows equivalent is) that specifies the text file and output directory. At that point you could set a cron job (or the Windows equivalent) to run it on a set interval.

I'd still want to be able to only download the updated pages but that will likely not be possible with most of the sites.

**Comment by SomeRandomDude870** [comment]
Ahhh okay,
I could make a simple bat for this, you are right.
Although, it would still be better to have it directly, especially if it´s possible to only update the new chapters and not download everything all the time anew.
