### ISSUE TITLE
Grab specific branches in CHYOA

### ISSUE THREAD

**Issue by TheEarlOfMarch** [theslavicbear/Ebook-Publisher#65]
Would it be possible to add the option to input a chapter and grab all following chapters? This would be really useful for large stories with big divergent branches where you might still want to grab all the sub-branches. Thanks!

**Comment by theslavicbear** [comment]
Would that be to say input any chapter and specify a subchapter for it to exclusively follow? Or add an option to pick any non-initial chapter and have it work forward instead of backwards?

**Comment by TheEarlOfMarch** [comment]
More the latter (input a specific chapter and have it log all the chapters forward. This would primarily be useful for stories like [The Gamer](https://chyoa.com/story/The-Gamer%2C-Chyoa-edition.12004), which have big distinct branches written by different authors.

**Comment by theslavicbear** [comment]
Added in version 3.2.0. Please note that the output files will still have the same filename, so if you are doing multiple branches, they may overwrite each other
