### ISSUE TITLE
Large file sizes

### ISSUE THREAD

**Issue by TheEarlOfMarch** [theslavicbear/Ebook-Publisher#66]
Again, thanks for making this tool! I've been looking for something like this for years. One thing I noticed while playing around with the Chyoa scraper was that it doesn't seem to account for branches that reconverge (e.g. multiple chapters have urls pointing to the same chapter). Right now, the scraper seems to treat each URL as a new chapter, causing it to download the same branches over and over again. It's not a big deal with small stories but it seems to get exponentially larger each time one of these branch merges happens (one of the stories I tested ended up having >50 copies of the same chapter with a final filesize of ~120mb).

Without any knowledge of how your code works, I think you might be able to use a dictionary to record whether a URL has been visited already and pair it with the internal address within the file. If you used the original URL as the key, you could use 'in' to quickly check if a new link already has an internal address saved and point a link towards that instead of redownloading the chapter.

**Comment by theslavicbear** [comment]
I was able to partially implement something similar for instances where linked chapters that link to an earlier chapter caused infinite loops, I might be able to do similar with forward links.

**Comment by theslavicbear** [comment]
This is mostly fixed in v3.1.4
