### ISSUE TITLE
Chyoa - never ending Cycle

### ISSUE THREAD

**Issue by SomeRandomDude870** [theslavicbear/Ebook-Publisher#67]
Story: Viral Transformation.

When I try to download this story it "downloads" it for roughly 20 Minutes, although it´s a short story. I have the feeling that it visits the same chapters several times.
After that time, I will get errors in between the chapter number and then it will keep downloading longer. And some when it just stops and does nothing anymore.

I guess it goes out of some reason back to older chapters whyever.

ummm, help?

**Comment by theslavicbear** [comment]
I'm planning to completely rewrite the code for chyoa stories to hopefully fix several of the issues.

**Comment by theslavicbear** [comment]
Can you please provide the link to the story? I can't find it immediately.

**Comment by theslavicbear** [comment]
This should be fixed in v3.1.4
