### ISSUE TITLE
Add the option to retrieve metadata from www.wlnupdates.com or www.novelupdates.com

### ISSUE THREAD

**Issue by Emasoft** [theslavicbear/Ebook-Publisher#70]
Can you add the option to retrieve metadata from www.wlnupdates.com or www.novelupdates.com ? So that all epub metadata fields are compiled when it saves it?

**Comment by Emasoft** [comment]
An extensive API is provided on both websites. You can check wlnupdates.com API here:

https://github.com/fake-name/wlnupdates/blob/master/app/templates/api-docs.md

**Comment by theslavicbear** [comment]
I probably won't work on this
