### ISSUE TITLE
CHYOA problem

### ISSUE THREAD

**Issue by defendurname** [theslavicbear/Ebook-Publisher#72]
Hello, I seem to have an error when trying to download a story from CHYOA. I get a ModuleNotFoundError: No module named 'requests'.

The story I am trying to download is:

https://chyoa.com/story/The-Gamer%2C-Chyoa-edition.12004

The command I am using is:

python3 Ebook-Publisher.py https://chyoa.com/story/The-Gamer%2C-Chyoa-edition.12004 -o epub -d D:\Documents\

Many thanks for your help.

**Comment by Lesutachi** [comment]
That is a Python problem. You either have to install the requests module with pip (by running `python3 -m pip install requests` for example) or your Python can't find it, and reinstalling 'requests' might solve it.

Try googling for `python ModuleNotFoundError: No module named 'requests'` and you'll find many results trying to solve your issue.

**Comment by defendurname** [comment]
Thanks! Your solution worked!
