### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by defendurname** [theslavicbear/Ebook-Publisher#73]
Hello, when using your program to download some stories from CHYOA.com it works fine but on a larger story I get this error:

RecursionError: maximum recursion depth exceeded while calling a Python object

The story I am downloading from has almost 1000 chapters here:

https://chyoa.com/chapter/Vacation-Week-2-%E2%80%93-A-Path-without-Destination.921081

Is it possible to alter the program do download larger stories or to download it in smaller chunks? Eg. For CHYOA it downloads from the last chapter you want and works backwards: could you tell it to stop at a certain point? Then you could download larger stories in chunks and it seems like something that could easily be done.

Many thanks for your help!

**Comment by SomeRandomDude870** [comment]
Where exactly is the error thrown?
 
And is the author still here? He said that he wants to rewrite it, but nothing happened.

**Comment by theslavicbear** [comment]
You can edit the max recursion depth with `sys.setrecursionlimit(99999)` Just add that to the beginning of the main file after the imports. Since it's a backwards download and not a forwards download it shouldn't be the issue with linked chapters.

I still want to rewrite the code for Chyoa but haven't made any progress in a long time.

**Comment by theslavicbear** [comment]
Yeah, I tried my above fix. I won't add it into the code since it bypasses Python's limits. Ideally, I could rewrite the code to not use recursion, but that isn't feasible with the current chyoa site. If they ever open up the story map without logging in, I might be able to manage it.
