### ISSUE TITLE
Better support for long CHYOA stories (The Gamer)

### ISSUE THREAD

**Issue by greenskye** [theslavicbear/Ebook-Publisher#81]
As far as I can tell it's currently impossible to download The Gamer with Ebook Publisher. If I start from the end, the story is currently 1036 chapters long and fails at roughly chapter 968 due to exceeding the recursion limits. This was marked as "wontfix" in issue #73. If you use the new "--chyoa-force-forwards" option it creates an ebook file with crazily long chapter files. Chapter 1036 would be over 1000 characters long with the 1.1.1.1.1.... etc naming method. This breaks the windows file path limits and also breaks Calibre and Sigil when I tried to open the file. The book stops once the file path's get too long.

My suggestion is to have a chapter depth variable that can be passed. This way I could download the book 100 chapters at a time and then merge them together (or just have Vol 1,2,3). This would also prevent file path too long errors.

**Comment by theslavicbear** [comment]
I could rewrite the reverse functions to be done iteratively rather than recursively so you could probably get the full story in one go. Adding a max page parameter probably isn't a bad idea either for a fall back.

Neither of those will help with forwards downloads though. That will require a redesign of how I handle the internal epub files, as well as the table of contents and probably some other stuff I can't remember.

**Comment by theslavicbear** [comment]
Reminder for myself to modify the filenames to be the chapter ranges with max chapter parameter

**Comment by theslavicbear** [comment]
The backwards functions have been updated to be iterative, not recursive. Request you to clone the test branch (https://github.com/theslavicbear/Ebook-Publisher/tree/feature-3.2) and try with the last page of the long story again. Also updated the forwards method but only with `-t` option for now. If your software can't handle it (which I doubt as Okular which I use chugs while trying to render it) then I'll start working on the max length parameter enhancement.
@greenskye

**Comment by greenskye** [comment]
Ok. So the backwards method now completely downloads the book. Thanks for the quick update!

The forwards method still suffers from the chapter file naming problem. The book downloads, but cannot be opened or used. At least on windows chapter title names of "1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1" do not work. For the forwards method, my guess is that you have a max depth of ~250 chapters, but probably less due to the name of the book, the folder it's in, etc all contributing to the file path length. It would be nice if the forward method worked, but I'm not sure on how you'd solve the naming problem. You have to name the chapters something, but I can't think of a naming strategy that would work for 1000+ chapter deep books while staying under ~200 characters.

The max page(chapter?) parameter would be far more useful. Even in The Gamer story there are several side stories which branch off at various points. Going backwards from the end skips these side stories, and going forward has the problem described above. If I could start from the end of a side story and pass in a max chapter value of "4" or something I could pull out just the side stories. Then I can merge these into the main book with a basic epub editor. Additionally it provides useful troubleshooting options as I can break a book into several smaller chunks which would've helped with the earlier recursive problem that you've just fixed.

As always I'm very grateful to your work on this program! It's been very useful to me and will remain useful even if you aren't interested in further enhancements.

**Comment by theslavicbear** [comment]
Oh I see what you mean. I figured the max chapter parameter would only be useful for going backwards, but it could work going forwards as well, though you might have to manage any branches that don't conclude before the cutoff (then again if they are that long you would just grab them separately I suppose).

For the file naming scheme, I think I can just give integer IDs to the chapters and keep track somehow. The depth strings that are used are mostly just for the TOC and end of chapter links I think. Actually, it might be easier than I think to change it, since it just loops through an array of them in order anyway.

It'll probably be a while until I'm able to work on these, so in the mean time you can try getting it as an HTML file and seeing if Calibre or whatever will take that, if not you can always use a browser to print to PDF in case that works.

**Comment by greenskye** [comment]
Sounds good! And ya I've just been creating several copies of the book from each of the different "end points" and then merging them together in Calibre.

**Comment by theslavicbear** [comment]
@greenskye
Okay, I think I fixed the chapter naming scheme so it won't overrun the filename limits. Request you clone the feature branch again and run it again. Seemed to work okay for me for The Gamer in Calibre.

**Comment by greenskye** [comment]
I'm not sure if this is just user error, but honestly the behavior seems the same (assuming we're still talking about the forward method. I double checked the file I downloaded and it seems to have the same edits I see in the most recent commit on 3.2: 
`c.append(epub.EpubHtml(title=site.chapters[i], file_name='nfChapter'+str(site.pageIDs[i-1])+'.xhtml', lang='en', tocTitle=str(' _'*int((len(site.depth[i-1])/2)+1))+' '+str(int((len(site.depth[i-1])/2)+2))+'.'+site.depth[i-1].split('.')[-1]+' '+site.chapters[i]))`

But as far as I can tell this still results in chapter file names that are 1.1.1.1. Calibre will add this book to my library, but breaks when I try to open, edit, convert or read the book. Sigil performs the same. And when I manually change the epub to a zip and unzip it in my root C/ drive it also fails with too long of a file path.

Attached the code that I downloaded in case I somehow grabbed the wrong thing.
[Ebook-Publisher-feature-3.2.zip](https://github.com/theslavicbear/Ebook-Publisher/files/7004169/Ebook-Publisher-feature-3.2.zip)

**Comment by theslavicbear** [comment]
The zip does seem to have the edits in it, I do see though that I forgot to change it for when the --chyoa-force-forwards option is used. Just fixed that

**Comment by greenskye** [comment]
That fixed it. The naming issue was never a problem for me going backwards, which was why I didn't test that method.

**Comment by theslavicbear** [comment]
Yeah going backwards it always just named the files 1, 2, 3, etc. Now let's see if I ever get around to trying to implement max chapter chapter depth.
