### ISSUE TITLE
SUpport for mcstories.com

### ISSUE THREAD

**Issue by thevoidwatches** [theslavicbear/Ebook-Publisher#84]
It would be great if support for mcstories.com could be added.

**Comment by theslavicbear** [comment]
Checked that site out. Looks like all of the stories are single page so this tool probably isn't needed. It should be sufficient to just save the html page, print the page to a .pdf, or simply copy and paste it.

**Comment by thevoidwatches** [comment]
Many stories are single page, but a great deal are have multiple chapters. [Here's one from the recent list that has 4 chapters](https://mcstories.com/BecomingDorothy/index.html) - I've seen and enjoyed stories with upwards of 20.
