### ISSUE TITLE
CHYOA site change issues cause script to not work

### ISSUE THREAD

**Issue by sammywasi** [theslavicbear/Ebook-Publisher#88]
In order to still be on Patreon CHYOA started hiding categories that were previously visible to only showing up to logged in members of more than a month. This has the unfortunate side effect of making the python script fail without throwing an error because to the script (and to people not logged into the site); the stories don't exist. 

I'm not exactly sure how this can be fixed without either bolting on the ability to add an end users login credentials; or using a common login in the script for downloading.

**Comment by theslavicbear** [comment]
Any specific stories you can point to to test? After adding in some dummy headers to the requests, I was able to download a mind control categorized story.

**Comment by theslavicbear** [comment]
I think I see what you mean now. Certain no-no words are just straight-up stripped out of titles and text if you aren't logged in. I think you're right in that the only fix is to include the user login cookie with the request.

![image](https://github.com/theslavicbear/Ebook-Publisher/assets/44584508/60657576-8289-49db-9e97-c986e688d174)
![image](https://github.com/theslavicbear/Ebook-Publisher/assets/44584508/f2e93b64-1897-4896-aa50-946bda885da6)

![image](https://github.com/theslavicbear/Ebook-Publisher/assets/44584508/aadeccd2-3399-4dee-92e5-d6d30c7812eb)
![image](https://github.com/theslavicbear/Ebook-Publisher/assets/44584508/3ac9e04a-6003-404c-82d5-d2c8d386a120)

**Comment by theslavicbear** [comment]
cool, I tested sending my session cookie with the request and was able to get the full version of the page. So either the quick fix where the user needs to supply the session cookie text to the script, or I figure out how to get one from the server by sending the login detail.

**Comment by theslavicbear** [comment]
request to pull latest code on the festure-3.3 branch to check if using the new --usr and ---pswd commands to supply your month old account allows access to the restricted stories.
